packages:
  - packages/*
  - playground/*
  - docs
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  brace-expansion: '>=5.0.8'
  vue: 3.6.0-rc.9
  '@vue/compiler-core': 3.6.0-rc.9
  '@vue/compiler-dom': 3.6.0-rc.9
  '@vue/compiler-sfc': 3.6.0-rc.9
  '@vue/compiler-ssr': 3.6.0-rc.9
  '@vue/compiler-vapor': 3.6.0-rc.9
  '@vue/reactivity': 3.6.0-rc.9
  '@vue/runtime-core': 3.6.0-rc.9
  '@vue/runtime-dom': 3.6.0-rc.9
  '@vue/runtime-vapor': 3.6.0-rc.9
  '@vue/server-renderer': 3.6.0-rc.9
  '@vue/shared': 3.6.0-rc.9
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.8 || 3.3.10'
  - vue-tsc@3.3.8 || 3.3.10
  - lint-staged@17.2.0
  - vue-component-type-helpers@3.3.8 || 3.3.10
  - vue@3.6.0-rc.9
  - '@vue/compiler-core@3.6.0-rc.9'
  - '@vue/compiler-dom@3.6.0-rc.9'
  - '@vue/compiler-sfc@3.6.0-rc.9'
  - '@vue/compiler-ssr@3.6.0-rc.9'
  - '@vue/compiler-vapor@3.6.0-rc.9'
  - '@vue/reactivity@3.6.0-rc.9'
  - '@vue/runtime-core@3.6.0-rc.9'
  - '@vue/runtime-dom@3.6.0-rc.9'
  - '@vue/runtime-vapor@3.6.0-rc.9'
  - '@vue/server-renderer@3.6.0-rc.9'
  - '@vue/shared@3.6.0-rc.9'
  - vue-component-meta@3.3.10
  - motion-v@2.4.0 || 2.4.4
  - '@intlify/core-base@11.4.12'
  - '@intlify/devtools-types@11.4.12'
  - '@intlify/message-compiler@11.4.12'
  - '@intlify/shared@11.4.12'
  - '@vueuse/core@15.0.0'
  - '@vueuse/metadata@15.0.0'
  - '@vueuse/shared@15.0.0'
  - unplugin-vue@8.0.0
  - unplugin@3.4.0
  - vue-i18n@11.4.12
