packages:
  - packages/*
  - playground/*
  - docs
allowBuilds:
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.8'
  - vue-tsc@3.3.8
  - lint-staged@17.2.0
  - vue-component-type-helpers@3.3.8
