// Hand-written on purpose: auto-extracting these from JSDoc would mean
// writing maintainer-facing prose twice (once for the component, once for
// itself). One line each, aimed at "what is this for," not implementation.
export const descriptions: Record<string, string> = {
  ConfigProvider:
    'Wraps your app to provide theming, i18n, and class-merging to every component below it.',
  Button: 'A clickable action with variants, sizes, loading states, and icon slots built in.',
  SplitButton: 'A primary action fused with a chevron that opens alternate actions in a dropdown.',
  Toolbar: 'A horizontal strip for grouping related actions, with roving keyboard focus.',
  SpeedDial: 'A floating action button that fans out into secondary actions on demand.',
  Dial: 'A circular drag control for picking a numeric value, like a volume knob.',
  SelectButton: 'A segmented control for choosing one (or several) values from a short list.',
  Input: 'A single-line text field with sizes, states, and slots for icons or hints.',
  Textarea: 'A multi-line text field that can auto-grow with its content.',
  InputNumber: 'A numeric field with increment/decrement controls and format-aware parsing.',
  OtpInput: 'A row of single-character boxes for one-time codes, with paste and auto-advance.',
  Checkbox: 'A tri-state toggle for a single yes/no/indeterminate choice.',
  Radio: 'One option in a mutually-exclusive set, always used inside a RadioGroup.',
  RadioGroup: 'Coordinates a set of Radio buttons so only one can be selected at a time.',
  Switch: 'An on/off toggle styled like a physical switch, for immediate-effect settings.',
  Slider: 'Drag a handle (or two, for a range) along a track to pick a numeric value.',
  Knob: 'A rotary control for picking a numeric value within a fixed arc.',
  Field: 'Wraps a form control with a label, help text, and error message, wired together for you.',
  DatePicker: 'A text field paired with a calendar popover for picking a date or range.',
  Calendar: 'A month grid for picking a single date, multiple dates, or a range.',
  FileUpload: 'A drop zone and file list for picking files, with validation and progress.',
  Select: 'A dropdown for picking one or more values from a list, with search and virtualization.',
  Combobox:
    'A searchable dropdown that also accepts free text, so autocomplete and tagging are one component.',
  CascadeSelect: 'A dropdown for picking a path through nested options, one level at a time.',
  Tree: 'A collapsible, indented list for hierarchical data with single or multi-selection.',
  TreeSelect: 'A dropdown whose panel is a Tree, for picking one or more nodes from a hierarchy.',
  Dialog: 'A modal overlay that interrupts the page until the user responds or dismisses it.',
  Popover: 'A floating panel anchored to a trigger element, for menus, forms, or extra detail.',
  Tooltip: 'A small floating label that appears on hover or focus to explain an element.',
  BottomSheet: 'A panel that slides up from the bottom edge, common on touch layouts.',
  ContextMenu:
    'A menu that opens at the pointer on right-click, replacing the native browser menu.',
  Menu: 'A dropdown list of actions opened from a trigger, with full keyboard navigation.',
  MenuList:
    'The same row rendering as Menu, but always in-flow, built for a permanent sidebar nav.',
  Tabs: 'Switches between panels of content, with a sliding indicator under the active tab.',
  Toaster: 'Renders the notifications created by toast(). Mount it once, anywhere in your app.',
  Message: 'An inline banner for status text: info, success, warning, or error.',
  Progress: 'A bar or ring showing completion of a determinate or indeterminate task.',
  Loader: 'A small spinner for indicating that something is in progress.',
  Skeleton: 'A placeholder shape that mimics real content while it is still loading.',
  DataTable:
    'A data grid with sorting, selection, resizing, and virtualization, composed from Columns.',
  Column: 'Defines one column of a DataTable, always used inside its tree.',
  Pagination: 'Page-number controls for splitting a long list or table across pages.',
  Card: 'A bordered container for grouping related content, with optional title and actions.',
  Avatar: 'A circular (or square) image or initials, representing a person or entity.',
  Badge: 'A small dot, count, or label overlaid on the corner of another element.',
  Tag: 'A compact label for categorizing or annotating an item inline.',
  Chip: 'A removable, compact token for selected filters, tags, or multi-select values.',
  Kbd: 'Styles a keyboard shortcut so it reads like a physical key.',
  Accordion: 'A stack of collapsible sections where opening one can close the others.',
  AccordionItem: 'One collapsible section of an Accordion, always used inside its tree.',
  Collapsible: 'A single show/hide section for content that is optional or secondary.',
  Separator: 'A thin line (or gap) for dividing content into visually distinct groups.',
  Resizable: 'A draggable handle for letting the user resize a panel between a min and max size.',
  SwipeToReveal: 'Swipe an item to reveal actions underneath it, like a native mobile list row.',
  PullToRefresh: 'A pull-down gesture at the top of a scroll container that triggers a refresh.',
  Dock: 'A macOS-style row of icons that magnify as the pointer approaches them.',
}
