// Side-effect-free: just the list, nothing else. Import this — not
// generate-vapor.mjs directly, which runs its own file-generation as a
// module-level side effect — wherever the canonical component name list is
// needed. generate-vapor.mjs and vael-ui-resolver's generate-manifest.mjs
// both consume this as their single source of truth.

// Add component name to include in the Vapor build / resolver manifest
// (Vapor dependencies auto-added by generate-vapor.mjs).
export const COMPONENTS = [
  'Accordion',
  'AccordionItem',
  'Avatar',
  'AvatarGroup',
  'Badge',
  'BottomSheet',
  'Breadcrumb',
  'BreadcrumbItem',
  'BreadcrumbSeparator',
  'Button',
  'ButtonGroup',
  'Calendar',
  'Card',
  'CascadeSelect',
  'Checkbox',
  'Chip',
  'Collapsible',
  'Column',
  'Combobox',
  'CommandPalette',
  'ConfigProvider',
  'ContextMenu',
  'DataTable',
  'DatePicker',
  'Dial',
  'Dialog',
  'DialogHost',
  'Dock',
  'Drawer',
  'Field',
  'FileUpload',
  'Input',
  'InputNumber',
  'Kbd',
  'Knob',
  'Loader',
  'Menu',
  'MenuList',
  'Message',
  'OtpInput',
  'Pagination',
  'PasswordInput',
  'Popover',
  'PopoverHost',
  'Progress',
  'PullToRefresh',
  'Radio',
  'RadioGroup',
  'Resizable',
  'ScrollArea',
  'Select',
  'SelectButton',
  'Separator',
  'Skeleton',
  'Slider',
  'Sortable',
  'SpeedDial',
  'SplitButton',
  'Stepper',
  'SwipeToReveal',
  'Switch',
  'Tabs',
  'Tag',
  'Textarea',
  'Toaster',
  'Toolbar',
  'Tooltip',
  'TooltipHost',
  'Tour',
  'Tree',
  'TreeSelect',
]
